// packages/react-tailwind-ts/src/components/PListItem.tsx
import { useState, useCallback } from "react";
import { clsx } from "clsx";

export interface PListItemProps {
    /** 标题 */
    Title: string;
    /** 信息/副标题 */
    Info?: string;
    /** 图标 (SVG path) */
    Logo?: string;
    /** 是否选中 */
    Checked?: boolean;
    /** 是否禁用 */
    IsEnabled?: boolean;
    /** 点击事件 */
    onClick?: () => void;
    /** 自定义类名 */
    className?: string;
}

export const PListItem: React.FC<PListItemProps> = ({
    Title,
    Info,
    Logo,
    Checked = false,
    IsEnabled = true,
    onClick,
    className,
}) => {
    const disabled = !IsEnabled;
    const [isHovered, setIsHovered] = useState(false);
    const [isPressed, setIsPressed] = useState(false);

    const handleClick = useCallback(() => {
        if (!disabled) onClick?.();
    }, [disabled, onClick]);

    const handleMouseEnter = useCallback(() => {
        setIsHovered(true);
    }, []);

    const handleMouseLeave = useCallback(() => {
        setIsHovered(false);
        setIsPressed(false);
    }, []);

    const handleMouseDown = useCallback(() => {
        if (!disabled) setIsPressed(true);
    }, [disabled]);

    const handleMouseUp = useCallback(() => {
        setIsPressed(false);
    }, []);

    return (
        <div
            className={clsx(
                "flex items-center h-10.5 px-2 rounded-[3px] transition-all duration-150",
                "cursor-pointer select-none",
                disabled && "cursor-not-allowed opacity-50",
                isHovered && !disabled && "bg-blue-50",
                className
            )}
            style={{
                transform: isPressed ? "scale(0.995)" : "scale(1)",
                transition: "transform 80ms ease-out, background-color 150ms",
            }}
            onClick={handleClick}
            onMouseEnter={handleMouseEnter}
            onMouseLeave={handleMouseLeave}
            onMouseDown={handleMouseDown}
            onMouseUp={handleMouseUp}>
            {/* 左侧指示条 */}
            <div
                className={clsx(
                    "w-0.5 h-6 rounded-full mr-2 transition-all duration-200",
                    Checked ? "bg-blue-400" : "bg-transparent"
                )}
            />

            {/* 图标 */}
            {Logo && (
                <svg
                    className={clsx(
                        "w-4 h-4 mr-3 shrink-0 transition-colors duration-150",
                        Checked ? "text-blue-400" : "text-gray-400",
                        isHovered && !disabled && !Checked && "text-blue-300"
                    )}
                    viewBox="0 0 24 24"
                    fill="currentColor">
                    <path d={Logo} />
                </svg>
            )}

            {/* 内容区域 */}
            <div className="flex-1 min-w-0">
                <div
                    className={clsx(
                        "text-[14px] truncate transition-colors duration-150",
                        Checked ? "text-blue-500 font-medium" : "text-gray-700",
                        isHovered && !disabled && !Checked && "text-blue-400"
                    )}>
                    {Title}
                </div>
                {Info && <div className="text-[12px] text-gray-400 truncate">{Info}</div>}
            </div>
        </div>
    );
};

export default PListItem;

// packages/vue-css-ts/src/components/PListItem.vue
<script setup lang="ts">
import { ref, computed } from "vue";

export interface PListItemProps {
    /** 标题 */
    Title: string;
    /** 信息/副标题 */
    Info?: string;
    /** 图标 (SVG path) */
    Logo?: string;
    /** 是否选中 */
    Checked?: boolean;
    /** 是否禁用 */
    IsEnabled?: boolean;
    /** 点击事件 */
    onClick?: () => void;
    /** 自定义类名 */
    className?: string;
}

const props = withDefaults(defineProps<PListItemProps>(), {
    Info: "",
    Logo: "",
    Checked: false,
    IsEnabled: true,
    className: "",
});

const emit = defineEmits<{
    click: [];
}>();

const disabled = computed(() => !props.IsEnabled);
const isHovered = ref(false);
const isPressed = ref(false);

const handleClick = () => {
    if (!disabled.value) {
        props.onClick?.();
        emit("click");
    }
};

const handleMouseEnter = () => {
    isHovered.value = true;
};

const handleMouseLeave = () => {
    isHovered.value = false;
    isPressed.value = false;
};

const handleMouseDown = () => {
    if (!disabled.value) isPressed.value = true;
};

const handleMouseUp = () => {
    isPressed.value = false;
};

// 指示条颜色
const indicatorColor = computed(() => {
    return props.Checked ? "#60a5fa" : "transparent"; // blue-400
});

// 图标颜色
const iconColor = computed(() => {
    if (props.Checked) return "#60a5fa"; // blue-400
    if (isHovered.value && !disabled.value && !props.Checked) return "#93c5fd"; // blue-300
    return "#9ca3af"; // gray-400
});

// 标题颜色
const titleColor = computed(() => {
    if (props.Checked) return "#3b82f6"; // blue-500
    if (isHovered.value && !disabled.value && !props.Checked) return "#60a5fa"; // blue-400
    return "#374151"; // gray-700
});
</script>

<template>
    <div
        class="p-list-item"
        :class="[className, { disabled, hovered: isHovered && !disabled }]"
        :style="{
            transform: isPressed ? 'scale(0.995)' : 'scale(1)',
        }"
        @click="handleClick"
        @mouseenter="handleMouseEnter"
        @mouseleave="handleMouseLeave"
        @mousedown="handleMouseDown"
        @mouseup="handleMouseUp">
        <!-- 左侧指示条 -->
        <div
            class="p-list-item-indicator"
            :style="{ backgroundColor: indicatorColor }"
        />

        <!-- 图标 -->
        <svg
            v-if="Logo"
            class="p-list-item-icon"
            :style="{ color: iconColor }"
            viewBox="0 0 24 24"
            fill="currentColor">
            <path :d="Logo" />
        </svg>

        <!-- 内容区域 -->
        <div class="p-list-item-content">
            <div
                class="p-list-item-title"
                :class="{ checked: Checked }"
                :style="{ color: titleColor }">
                {{ Title }}
            </div>
            <div v-if="Info" class="p-list-item-info">{{ Info }}</div>
        </div>
    </div>
</template>

<style scoped>
.p-list-item {
    display: flex;
    align-items: center;
    height: 42px;
    padding: 0 8px;
    border-radius: 3px;
    cursor: pointer;
    user-select: none;
    transition: transform 80ms ease-out, background-color 150ms;
}

.p-list-item.hovered {
    background-color: #eff6ff;
}

.p-list-item.disabled {
    cursor: not-allowed;
    opacity: 0.5;
}

.p-list-item-indicator {
    width: 2px;
    height: 24px;
    border-radius: 9999px;
    margin-right: 8px;
    transition: all 200ms;
}

.p-list-item-icon {
    width: 16px;
    height: 16px;
    margin-right: 12px;
    flex-shrink: 0;
    transition: color 150ms;
}

.p-list-item-content {
    flex: 1;
    min-width: 0;
}

.p-list-item-title {
    font-size: 14px;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
    transition: color 150ms;
}

.p-list-item-title.checked {
    font-weight: 500;
}

.p-list-item-info {
    font-size: 12px;
    color: #9ca3af;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
}
</style>
